# Generated by Django 5.1.3 on 2026-01-15 16:06

import apps.usuario.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuario.models.UsuarioManager()),
            ],
        ),
    ]
