# Generated by Django 5.1.3 on 2026-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='unidad_medida_prefer',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', max_length=10),
        ),
    ]
