# Generated by Django 5.1.3 on 2026-05-25 (Manual data migration)

from django.db import migrations

def cargar_roles(apps, schema_editor):
    Rol = apps.get_model("usuario", "Rol")
    
    roles_a_cargar = [
        {
            "codigo": "ADMIN",
            "descripcion": "Administrador del sistema, con acceso total a todas las funciones y configuraciones.",
        },
        {
            "codigo": "OPERADOR",
            "descripcion": "Operador del sistema, capacitado para registrar pesadas y consultar datos básicos.",
        },
        {
            "codigo": "LECTOR",
            "descripcion": "Usuario lector, con permisos únicamente para visualizar pesadas e historiales sin realizar modificaciones.",
        },
    ]
    
    for r in roles_a_cargar:
        Rol.objects.get_or_create(
            codigo=r["codigo"],
            defaults={"descripcion": r["descripcion"], "activo": True}
        )

def revertir_roles(apps, schema_editor):
    Rol = apps.get_model("usuario", "Rol")
    Rol.objects.filter(codigo__in=["ADMIN", "OPERADOR", "LECTOR"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_unidad_medida_prefer'),
    ]

    operations = [
        migrations.RunPython(cargar_roles, reverse_code=revertir_roles),
    ]
