# Generated by Django 5.1.3 on 2026-01-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], max_length=5)),
                ('valida', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesadas', to='animal.animal')),
            ],
        ),
    ]
