# Generated by Django 5.1.3 on 2026-01-14 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesada', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesada',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='pesada',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pesada',
            name='hora',
        ),
        migrations.AddField(
            model_name='pesada',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
