# Generated by Django 5.1 on 2026-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesada', '0003_remove_pesada_creada_en_remove_pesada_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesada',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
