# Generated by Django 5.1.3 on 2026-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesada', '0004_pesada_peso_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesada',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
