# Generated by Django 5.1.3 on 2026-05-25 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesada', '0005_alter_pesada_peso_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesada',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
