# Generated by Django 5.1.3 on 2026-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesada', '0006_alter_pesada_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesada',
            name='uuid_cliente',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
