# Generated by Django 5.1.3 on 2026-08-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('pesada', '0007_pesada_uuid_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesada',
            name='caravana_desconocida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesadas', to='animal.animal'),
        ),
    ]
