# Generated by Django 5.1.3 on 2026-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_identificacion', models.CharField(max_length=50, unique=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
